# Generated by Django 5.0.6 on 2024-06-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('is_confirmed', models.BooleanField(blank=True, default=False, help_text='Был ли уже оформлен заказ', verbose_name='Подтверждение заказа')),
                ('status', models.CharField(choices=[('Без статуса', 'Без статуса'), ('Обработка заказа', 'Обработка заказа'), ('Ожидает самовывоза', 'Ожидает самовывоза'), ('Выдан', 'Выдан'), ('Отменен клиентом', 'Отменен клиентом'), ('Отменен магазином', 'Отменен магазином'), ('Возврат', 'Возврат')], default='Без статуса', max_length=50, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('price_at_time_of_order', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена товара при заказе')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
    ]
