# Generated by Django 5.0.6 on 2024-07-02 07:57

import shop.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProductCSVLoader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_products_files/', validators=[shop.validators.validate_csv_file])),
            ],
            options={
                'verbose_name': 'Загрузка новых товаров',
                'verbose_name_plural': 'Загрузка новых товаров',
            },
        ),
    ]
